apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: mailsubscription
spec:
  topic: msgqueue
  routes:
    default: /queuelisten
  pubsubname: pubsub
scopes:
  - manager-service
  - submanager-service
